const TelegramBot = require('node-telegram-bot-api');
const { TelegramClient, Api } = require('telegram');
const { StringSession } = require('telegram/sessions');
const fetch = require('node-fetch');
const http = require('http');

const PORT = process.env.PORT || 3000;
http.createServer((req, res) => { res.writeHead(200); res.end("Bot işləyir."); }).listen(PORT, () => {
  console.log(`Health-check serveri ${PORT} portunda işə düşdü.`);
});

const BOT_TOKEN = "8940602664:AAHbe3HRkoselmfmUgmzvwWuJFfPkrCnKUg";
const API_ID = 36726228;
const API_HASH = "59b3c57e519c9cf2463b8725bc7c4f36";
const FIREBASE_URL = "https://newbot-db894-default-rtdb.europe-west1.firebasedatabase.app";

const bot = new TelegramBot(BOT_TOKEN, { polling: true });
const userSessions = {};      // normal yeni-nömrə axını üçün keçici sessiyalar
const adminSessions = {};     // admin tərəfindən dəyişdirilən nömrə üçün OTP sessiyaları
const adminAuthInFlight = {}; // eyni lisenziyanın iki dəfə emal edilməsinin qarşısı
const menuState = {};         // chatId -> { id, type: 'text'|'photo' } (KOMPAKT MENYU)

console.log("EliteBot Serveri Başladı...");

const i18n = {
    az: {
        sub_msg: "Aşağıdakı kanallara abunə olun:", sub_btn: "✅ Abunəlikləri Təsdiqlə", checking: "⏳ Abunəlik yoxlanılır...",
        confirmed: "✅ Təsdiqləndi!", not_subscribed: "❌ Siz hələ bütün kanallara abunə olmamısınız! Zəhmət olmasa əvvəlcə kanallara qoşulun və yenidən yoxlayın.",
        menu_unlic: "Zəhmət olmasa lisenziya aktivləşdirin:", btn_act_lic: "🔑 Lisenziya Aktivləşdir",
        btn_buy_lic: "🛒 Lisenziya Al / Dəstək", btn_price: "📋 Qiymət Cədvəli", btn_web: "🌐 Web Sitemiz",
        menu_lic: "✅ Lisenziya Aktivdir! Ana Menyu:", btn_add_num: "➕ Yeni Nömrə Əlavə Et", btn_manage: "⚙️ Hesablarım (Nömrələr)",
        enter_lic: "Lisenziya kodunu daxil edin (Məsələn: ELITE-12345):", invalid_lic: "❌ Keçərsiz lisenziya kodu formati.",
        not_found_lic: "❌ Belə bir lisenziya bazada mövcud deyil!", blocked_lic: "❌ Bu lisenziya bloklanıb!",
        used_lic: "❌ Bu lisenziya artıq başqa istifadəçi tərəfindən istifadə olunur!", success_lic: "✅ Lisenziya uğurla təsdiqləndi!",
        no_lic: "❌ Aktiv lisenziyanız yoxdur.", limit_reached: "❌ Lisenziya limitinizə çatdınız (Maksimum: {max} nömrə).",
        enter_phone: "📱 Bota qoşmaq istədiyiniz Telegram nömrənizi daxil edin (+ işarəsi ilə. Məs: +994501234567):",
        no_numbers: "⚠️ Hələ heç bir nömrə əlavə edilməyib.", my_accounts: "⚙️ Aktiv Hesablarınız:\n\n",
        stopped: "🔴 Dayandırılıb", active: "🟢 Aktiv", stop_btn: "Dayandır: +", resume_btn: "Başlat: +", back_main: "🔙 Ana Menyu",
        phone_format: "⚠️ Nömrə '+' ilə başlamalıdır!", otp_sent: "⏳ OTP kodu göndərilir, gözləyin...",
        otp_info: "📩 Təhlükəsizlik kodu göndərildi. Kodu aralarında boşluqla daxil edin (Məs: 8 8 9 9 0):\n\nNömrəni səhv daxil etmisinizsə, /changenumber yazın.",
        err: "❌ Xəta: ", sess_lost: "⚠️ Sessiya yaddaşdan silinib. Zəhmət olmasa prosesə yenidən başlayın.",
        login_success: "✅ {phone} hesabına uğurla giriş edildi!\n\nİndi mesajın göndəriləcəyi qrupun istifadəçi adını (məs: @qrupadim) və ya linkini göndərin:",
        otp_err: "❌ OTP səhvdir və ya hesabda 2-Mərhələli təsdiqləmə (2FA) aktivdir. Xəta: ",
        group_added: "✅ Qrup əlavə olundu. (Hazırda bu nömrə üçün {count} qrup var)\n\nBaşqa qrup əlavə etmək istəyirsiniz, yoxsa davam edək?",
        add_more: "➕ Başqa qrup əlavə et", finish_btn: "✅ Bitir və Davam Et", send_group: "Əlavə etmək istədiyiniz qrupun istifadəçi adını və ya linkini göndərin:",
        ask_interval: "✅ Qruplar təsdiqləndi. İndi mesajın neçə dəqiqədən bir atılacağını rəqəmlə yazın (Məs: 2, 3, 5):",
        interval_err: "⚠️ Zəhmət olmasa 2 ilə 60 arası bir rəqəm yazın.",
        bot_started: "✅ Bot İşə Düşdü ({phone})!\n\nBot hər {min} dəqiqədən bir seçdiyiniz mənbədən ən son mesajı hədəf qruplara atacaq.",
        ch1_btn: "📢 Məcburi Kanal 1", ch2_btn: "📢 Məcburi Kanal 2", all_stopped: "⏹ Bütün hesablar dayandırıldı.", stop_single: "⏹ +{phone} üçün göndərim dayandırıldı.",
        resume_single: "▶️ +{phone} yenidən işə düşdü.", enter_again: "🔄 Telefon nömrənizi yenidən daxil edin (+ işarəsi ilə):",
        source_title: "📥 Mesaj mənbəyini seçin:",
        source_saved_btn: "📥 Qeyd Olunmuş Mesajlar (Saved)",
        source_channel_btn: "📢 Kanal / Qrup",
        enter_source_channel: "📢 Mesajın çəkiləcəyi kanalın/qrupun istifadəçi adını və ya linkini göndərin (Məs: @kanaladi):",
        source_channel_err: "❌ Mənbə kanal/qrup tapılmadı və ya mesaj oxunmadı. Linki yoxlayıb yenidən göndərin.\nXəta: ",
        source_label_saved: "📥 Qeyd olunmuş mesajlar (Saved)",
        source_label_channel: "📥 Mənbə: Kanal/Qrup — {channel}",
        change_src_btn: "🔁 Mənbəni Dəyiş: +",
        del_acct_btn: "🗑 Nömrəni Sil: +",
        acct_deleted: "🗑 +{phone} nömrəsi hesablarınızdan silindi.",
        groups_label: "🎯 Hədəf Qruplar:",
        no_groups: "— Qrup yoxdur",
        del_grp_btn: "✖️ {group}",
        grp_deleted: "🗑 Qrup silindi.",
        src_del_btn: "🗑 Mənbəni Sil: +",
        src_deleted: "✅ Mənbə silindi. İndi mesajlar Qeyd Olunmuş Mesajlardan (Saved) çəkilir.",
        add_grp_btn: "➕ Qrup Əlavə Et: +",
        back_manage_btn: "🔙 Hesablarım",
        admin_change_msg: "🔁 Administrator hesab nömrənizi dəyişdi. Yeni nömrəyə ({phone}) Telegram təsdiq kodu göndərildi. Kodu aralarında boşluqla daxil edin:",
        admin_change_done: "✅ Yeni nömrə (+{phone}) uğurla təsdiqləndi! Bütün qruplar, interval və mənbə qorundu.",
        admin_change_err: "❌ Yeni nömrəyə kod göndərilə bilmədi. Xəta: ",
        admin_no_acc: "⚠️ Bu lisenziyada nömrə tapılmadı. Dəyişiklik ləğv edildi."
    },
    tr: {
        sub_msg: "Aşağıdaki kanallara abone olun:", sub_btn: "✅ Abonelikleri Onayla", checking: "⏳ Abonelik kontrol ediliyor...",
        confirmed: "✅ Onaylandı!", not_subscribed: "❌ Henüz tüm kanallara abone olmadınız! Lütfen önce kanallara katılın ve tekrar deneyin.",
        menu_unlic: "Lütfen lisansınızı aktifleştirin:", btn_act_lic: "🔑 Lisansı Aktifleştir",
        btn_buy_lic: "🛒 Lisans Al / Destek", btn_price: "📋 Fiyat Listesi", btn_web: "🌐 Web Sitemiz",
        menu_lic: "✅ Lisans Aktif! Ana Menü:", btn_add_num: "➕ Yeni Numara Ekle", btn_manage: "⚙️ Hesaplarım (Numaralar)",
        enter_lic: "Lisans kodunu girin (Örn: ELITE-12345):", invalid_lic: "❌ Geçersiz lisans kodu formatı.",
        not_found_lic: "❌ Böyle bir lisans veritabanında mevcut değil!", blocked_lic: "❌ Bu lisans engellendi!",
        used_lic: "❌ Bu lisans zaten başka bir kullanıcı tarafından kullanılıyor!", success_lic: "✅ Lisans başarıyla onaylandı!",
        no_lic: "❌ Aktif lisansınız yok.", limit_reached: "❌ Lisans limitinize ulaştınız (Maksimum: {max} numara).",
        enter_phone: "📱 Bota bağlamak istediğiniz Telegram numaranızı girin (+ işareti ile. Örn: +994501234567):",
        no_numbers: "⚠️ Henüz hiç numara eklenmedi.", my_accounts: "⚙️ Aktif Hesaplarınız:\n\n",
        stopped: "🔴 Durduruldu", active: "🟢 Aktif", stop_btn: "Durdur: +", resume_btn: "Başlat: +", back_main: "🔙 Ana Menü",
        phone_format: "⚠️ Numara '+' ile başlamalıdır!", otp_sent: "⏳ OTP kodu gönderiliyor, bekleyin...",
        otp_info: "📩 Güvenlik kodu gönderildi. Kodu aralarında boşluk bırakarak girin (Örn: 8 8 9 9 0):\n\nNumarayı yanlış girdiyseniz, /changenumber yazın.",
        err: "❌ Hata: ", sess_lost: "⚠️ Oturum bellekten silindi. Lütfen işleme yeniden başlayın.",
        login_success: "✅ {phone} hesabına başarıyla giriş yapıldı!\n\nŞimdi mesajın gönderileceği grubun kullanıcı adını (örn: @grupadi) veya linkini gönderin:",
        otp_err: "❌ OTP yanlış veya hesapta 2 Adımlı Doğrulama (2FA) aktif. Hata: ",
        group_added: "✅ Grup eklendi. (Şu anda bu numara için {count} grup var)\n\nBaşka grup eklemek ister misiniz, yoksa devam edelim mi?",
        add_more: "➕ Başka grup ekle", finish_btn: "✅ Bitir ve Devam Et", send_group: "Eklemek istediğiniz grubun kullanıcı adını veya linkini gönderin:",
        ask_interval: "✅ Gruplar onaylandı. Şimdi mesajın kaç dakikada bir atılacağını rakamla yazın (Örn: 2, 3, 5):",
        interval_err: "⚠️ Lütfen 2 ile 60 arası bir rakam yazın.",
        bot_started: "✅ Bot Çalışmaya Başladı ({phone})!\n\nBot her {min} dakikada bir seçtiğiniz kaynaktan en son mesajı hedef gruplara atacak.",
        ch1_btn: "📢 Zorunlu Kanal 1", ch2_btn: "📢 Zorunlu Kanal 2", all_stopped: "⏹ Tüm hesaplar durduruldu.", stop_single: "⏹ +{phone} için gönderim durduruldu.",
        resume_single: "▶️ +{phone} yeniden çalışmaya başladı.", enter_again: "🔄 Telefon numaranızı yeniden girin (+ işareti ile):",
        source_title: "📥 Mesaj kaynağını seçin:",
        source_saved_btn: "📥 Kayıtlı Mesajlar (Saved)",
        source_channel_btn: "📢 Kanal / Grup",
        enter_source_channel: "📢 Mesajın çekileceği kanalın/grubun kullanıcı adını veya linkini gönderin (Örn: @kanaladi):",
        source_channel_err: "❌ Kaynak kanal/grup bulunamadı veya mesaj okunamadı. Lütfen linki kontrol edip tekrar gönderin.\nHata: ",
        source_label_saved: "📥 Kayıtlı mesajlar (Saved)",
        source_label_channel: "📥 Kaynak: Kanal/Grup — {channel}",
        change_src_btn: "🔁 Kaynağı Değiştir: +",
        del_acct_btn: "🗑 Numarayı Sil: +",
        acct_deleted: "🗑 +{phone} numarası hesaplarınızdan silindi.",
        groups_label: "🎯 Hedef Gruplar:",
        no_groups: "— Grup yok",
        del_grp_btn: "✖️ {group}",
        grp_deleted: "🗑 Grup silindi.",
        src_del_btn: "🗑 Kaynağı Sil: +",
        src_deleted: "✅ Kaynak silindi. Artık mesajlar Kayıtlı Mesajlardan (Saved) çekilecek.",
        add_grp_btn: "➕ Grup Ekle: +",
        back_manage_btn: "🔙 Hesaplarım",
        admin_change_msg: "🔁 Yönetici hesap numaranızı değiştirdi. Yeni numaraya ({phone}) Telegram onay kodu gönderildi. Kodu aralarında boşluk bırakarak girin:",
        admin_change_done: "✅ Yeni numara (+{phone}) başarıyla onaylandı! Tüm gruplar, aralık ve kaynak korundu.",
        admin_change_err: "❌ Yeni numaraya kod gönderilemedi. Hata: ",
        admin_no_acc: "⚠️ Bu lisansta numara bulunamadı. Değişiklik iptal edildi."
    },
    en: {
        sub_msg: "Please subscribe to the channels below:", sub_btn: "✅ Confirm Subscriptions", checking: "⏳ Checking subscription...",
        confirmed: "✅ Confirmed!", not_subscribed: "❌ You haven't subscribed to all the channels yet! Please join the channels first and check again.",
        menu_unlic: "Please activate your license:", btn_act_lic: "🔑 Activate License",
        btn_buy_lic: "🛒 Buy License / Support", btn_price: "📋 Price List", btn_web: "🌐 Our Website",
        menu_lic: "✅ License Active! Main Menu:", btn_add_num: "➕ Add New Number", btn_manage: "⚙️ My Accounts (Numbers)",
        enter_lic: "Enter your license code (e.g: ELITE-12345):", invalid_lic: "❌ Invalid license code format.",
        not_found_lic: "❌ No such license exists in the database!", blocked_lic: "❌ This license has been blocked!",
        used_lic: "❌ This license is already being used by another user!", success_lic: "✅ License successfully confirmed!",
        no_lic: "❌ You don't have an active license.", limit_reached: "❌ You have reached your license limit (Maximum: {max} numbers).",
        enter_phone: "📱 Enter the Telegram number you want to connect to the bot (with '+', e.g: +994501234567):",
        no_numbers: "⚠️ No numbers have been added yet.", my_accounts: "⚙️ Your Active Accounts:\n\n",
        stopped: "🔴 Stopped", active: "🟢 Active", stop_btn: "Stop: +", resume_btn: "Start: +", back_main: "🔙 Main Menu",
        phone_format: "⚠️ The number must start with '+'!", otp_sent: "⏳ Sending OTP code, please wait...",
        otp_info: "📩 Security code sent. Enter the code with spaces between digits (e.g: 8 8 9 9 0):\n\nIf you entered the wrong number, type /changenumber.",
        err: "❌ Error: ", sess_lost: "⚠️ Session was cleared from memory. Please start the process again.",
        login_success: "✅ Successfully logged into {phone}!\n\nNow send the username (e.g: @groupname) or link of the group you want to send messages to:",
        otp_err: "❌ OTP is incorrect or 2-Step Verification (2FA) is active on the account. Error: ",
        group_added: "✅ Group added. (Currently {count} group(s) for this number)\n\nWould you like to add another group, or continue?",
        add_more: "➕ Add another group", finish_btn: "✅ Finish and Continue", send_group: "Send the username or link of the group you want to add:",
        ask_interval: "✅ Groups confirmed. Now enter the number of minutes between each message (e.g: 2, 3, 5):",
        interval_err: "⚠️ Please enter a number between 2 and 60.",
        bot_started: "✅ *Bot Started ({phone})!*\n\nThe bot will send the latest message from your chosen source to the target groups every {min} minutes.",
        ch1_btn: "📢 Required Channel 1", ch2_btn: "📢 Required Channel 2", all_stopped: "⏹ All accounts stopped.", stop_single: "⏹ Sending stopped for +{phone}.",
        resume_single: "▶️ +{phone} started again.", enter_again: "🔄 Enter your phone number again (with '+'):",
        source_title: "📥 Choose message source:",
        source_saved_btn: "📥 Saved Messages",
        source_channel_btn: "📢 Channel / Group",
        enter_source_channel: "📢 Send the username or link of the channel/group to pull messages from (e.g: @channelname):",
        source_channel_err: "❌ Source channel/group not found or message could not be read. Check the link and send again.\nError: ",
        source_label_saved: "📥 Saved Messages",
        source_label_channel: "📥 Source: Channel/Group — {channel}",
        change_src_btn: "🔁 Change Source: +",
        del_acct_btn: "🗑 Delete Number: +",
        acct_deleted: "🗑 +{phone} has been deleted from your accounts.",
        groups_label: "🎯 Target Groups:",
        no_groups: "— No groups",
        del_grp_btn: "✖️ {group}",
        grp_deleted: "🗑 Group deleted.",
        src_del_btn: "🗑 Delete Source: +",
        src_deleted: "✅ Source deleted. Messages will now be pulled from Saved Messages.",
        add_grp_btn: "➕ Add Group: +",
        back_manage_btn: "🔙 My Accounts",
        admin_change_msg: "🔁 Admin changed your account number. A Telegram confirmation code was sent to the new number ({phone}). Enter the code with spaces between digits:",
        admin_change_done: "✅ New number (+{phone}) confirmed successfully! All groups, interval and source were preserved.",
        admin_change_err: "❌ Could not send code to the new number. Error: ",
        admin_no_acc: "⚠️ No number found for this license. Change cancelled."
    },
    ru: {
        sub_msg: "Подпишитесь на следующие каналы:", sub_btn: "✅ Подтвердить подписки", checking: "⏳ Проверка подписки...",
        confirmed: "✅ Подтверждено!", not_subscribed: "❌ Вы ещё не подписались на все каналы! Пожалуйста, сначала подпишитесь на каналы и проверьте снова.",
        menu_unlic: "Пожалуйста, активируйте лицензию:", btn_act_lic: "🔑 Активировать лицензию",
        btn_buy_lic: "🛒 Купить лицензию / Поддержка", btn_price: "📋 Прайс-лист", btn_web: "🌐 Наш сайт",
        menu_lic: "✅ Лицензия активна! Главное меню:", btn_add_num: "➕ Добавить новый номер", btn_manage: "⚙️ Мои аккаунты (Номера)",
        enter_lic: "Введите код лицензии (Напр: ELITE-12345):", invalid_lic: "❌ Неверный формат кода лицензии.",
        not_found_lic: "❌ Такой лицензии нет в базе данных!", blocked_lic: "❌ Эта лицензия заблокирована!",
        used_lic: "❌ Эта лицензия уже используется другим пользователем!", success_lic: "✅ Лицензия успешно подтверждена!",
        no_lic: "❌ У вас нет активной лицензии.", limit_reached: "❌ Вы достигли лимита лицензии (Максимум: {max} номеров).",
        enter_phone: "📱 Введите номер Telegram, который хотите подключить к боту (с '+', напр: +994501234567):",
        no_numbers: "⚠️ Пока не добавлено ни одного номера.", my_accounts: "⚙️ Ваши активные аккаунты:\n\n",
        stopped: "🔴 Остановлен", active: "🟢 Активен", stop_btn: "Остановить: +", resume_btn: "Запустить: +", back_main: "🔙 Главное меню",
        phone_format: "⚠️ Номер должен начинаться с '+'!", otp_sent: "⏳ Отправка OTP-кода, подождите...",
        otp_info: "📩 Код безопасности отправлен. Введите код с пробелами между цифрами (напр: 8 8 9 9 0):\n\nЕсли вы ввели неверный номер, напишите /changenumber.",
        err: "❌ Ошибка: ", sess_lost: "⚠️ Сессия удалена из памяти. Пожалуйста, начните процесс заново.",
        login_success: "✅ Вход в аккаунт {phone} выполнен успешно!\n\nТеперь отправьте имя пользователя (напр: @имягруппы) или ссылку группы, куда будут отправляться сообщения:",
        otp_err: "❌ Неверный OTP или на аккаунте включена двухфакторная аутентификация (2FA). Ошибка: ",
        group_added: "✅ Группа добавлена. (Сейчас для этого номера {count} групп(а))\n\nХотите добавить ещё одну группу или продолжить?",
        add_more: "➕ Добавить ещё группу", finish_btn: "✅ Завершить и продолжить", send_group: "Отправьте имя пользователя или ссылку группы, которую хотите добавить:",
        ask_interval: "✅ Группы подтверждены. Теперь укажите число, через сколько минут будет отправляться сообщение (напр: 2, 3, 5):",
        interval_err: "⚠️ Пожалуйста, введите число от 2 до 60.",
        bot_started: "✅ *Бот запущен ({phone})!*\n\nБот будет отправлять последнее сообщение из выбранного вами источника в целевые группы каждые {min} минут.",
        ch1_btn: "📢 Обязательный канал 1", ch2_btn: "📢 Обязательный канал 2", all_stopped: "⏹ Все аккаунты остановлены.", stop_single: "⏹ Отправка для +{phone} остановлена.",
        resume_single: "▶️ +{phone} снова запущен.", enter_again: "🔄 Введите ваш номер телефона заново (с '+'):",
        source_title: "📥 Выберите источник сообщений:",
        source_saved_btn: "📥 Сохранённые сообщения",
        source_channel_btn: "📢 Канал / Группа",
        enter_source_channel: "📢 Отправьте имя пользователя или ссылку канала/группы, откуда брать сообщения (напр: @имяканала):",
        source_channel_err: "❌ Источник канал/группа не найден или сообщение не удалось прочитать. Проверьте ссылку и отправьте снова.\nОшибка: ",
        source_label_saved: "📥 Сохранённые сообщения",
        source_label_channel: "📥 Источник: Канал/Группа — {channel}",
        change_src_btn: "🔁 Изменить источник: +",
        del_acct_btn: "🗑 Удалить номер: +",
        acct_deleted: "🗑 +{phone} удалён из ваших аккаунтов.",
        groups_label: "🎯 Целевые группы:",
        no_groups: "— Групп нет",
        del_grp_btn: "✖️ {group}",
        grp_deleted: "🗑 Группа удалена.",
        src_del_btn: "🗑 Удалить источник: +",
        src_deleted: "✅ Источник удалён. Теперь сообщения берутся из Сохранённых сообщений.",
        add_grp_btn: "➕ Добавить группу: +",
        back_manage_btn: "🔙 Мои аккаунты",
        admin_change_msg: "🔁 Администратор изменил номер аккаунта. На новый номер ({phone}) отправлен код подтверждения Telegram. Введите код с пробелами между цифрами:",
        admin_change_done: "✅ Новый номер (+{phone}) успешно подтверждён! Все группы, интервал и источник сохранены.",
        admin_change_err: "❌ Не удалось отправить код на новый номер. Ошибка: ",
        admin_no_acc: "⚠️ Для этой лицензии номер не найден. Изменение отменено."
    }
};

function t(key, lang = 'az', params = {}) {
    let text = i18n[lang]?.[key]